---
- hosts: vminfra
  tasks:
    - name: "Registry Git-Runner"
      shell: sudo docker exec gitlab-runner gitlab-runner register \
                   --non-interactive \
                   --url "$URL" \
                   --registration-token "$TOKENREG" \
                   --executor "shell" \
                   --description "shell-using" \
                   --clone-url "$URL" \
                   --run-untagged="true" \
                   --locked="false" \
                   --access-level="not_protected"
      become: yes             